### ISSUE TITLE
Unhashable type in _load_dict

### ISSUE THREAD

**Issue by druedaplata** [TNick/pyl2extra#2] opened 2015-06-24 15:16 UTC
There is a problem in [this](https://github.com/TNick/pyl2extra/blob/master/pyl2extra/datasets/images.py#L295) line, it seems that _convert('RGB')_ returns a not hashable object it can't be used as key in an OrderedDict()

**Comment by TNick** [comment] 2015-06-24 18:28
Hello and thanks for reporting.
The [tests](https://github.com/TNick/pyl2extra/blob/master/pyl2extra/datasets/tests/test_images.py) are passing on my computer

```
Python 2.7.10 :: Anaconda 2.1.0 (64-bit)
```

Please share some code and the python version.

**Comment by druedaplata** [comment] 2015-06-24 19:13
```
import collections
from PIL import Image

img = 'some_image.jpg'
imgin = Image.open(img)
imgin = imgin.convert('RGB')

result = collections.OrderedDict()
result[imgin] = 0
```

Doing this i get the same error from [here](https://github.com/TNick/pyl2extra/blob/master/pyl2extra/datasets/images.py#L276)

```
Python 2.7.10 :: Anaconda 2.2.0 (64-bit)
```

**Comment by TNick** [comment] 2015-06-24 19:28
Actually I think this is a PIL issue. And this is an opportunity to add proper dependency.
I have 

``` bash
conda list | grep pil
# or
pip show pil && pip show pillow
pil                       1.1.7                    py27_1  
pillow                    2.8.2                     <pip>
```

I am not sure if pillow is required. Can you please check? I suspect pillow should be added to the list of dependencies.
If this ends up eating too much time I will switch to using numpy arrays instead of images.

**Comment by druedaplata** [comment] 2015-06-24 19:41
I updated pillow in my computer.

```
pillow:    2.7.0-py27_1 --> 2.8.2-py27_0
```

but the problem remains the same.

**Comment by TNick** [comment] 2015-06-24 19:53
I can reproduce it by changing 

```
import Image
```

to

```
from PIL import Image
```

Thus the problem is pillow.
I'm going to switch from Image to numpy arrays and close this bug when tests are passing.
Thanks again for reporting.

---

[Link](http://stackoverflow.com/questions/31029974/unhashable-instance-with-ordereddict) to SO question.

**Closed as completed** 2015-06-24 20:38 UTC
Labels: bug
